(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"2_html_atlas_1", frames: [[0,0,640,853],[0,855,640,800]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.christinetrantaj1B4wkOCpIunsplash = function() {
	this.initialize(ss["2_html_atlas_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.maemu8Vh6ulKc50ounsplash = function() {
	this.initialize(ss["2_html_atlas_1"]);
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.photo1527661591475527312dd65f5 = function() {
	this.initialize(img.photo1527661591475527312dd65f5);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,2158,3021);


// stage content:
(lib._2html = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// 遮色片 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("Ag4BQQgYgXAAgiIAAAAQAAgcATgWIAAAAQgIAEgKAAIAAAAQgRAAgLgMIAAAAQgMgLAAgRIAAAAQAAgQAMgMIAAAAQALgMARAAIAAAAQAQAAAMAMIAAAAQAMAMAAAQIAAAAQAAAMgGAJIAAAAQAUgOAZAAIAAAAQAbAAAUAQIAAAAQgHgKAAgNIAAAAQAAgQAMgMIAAAAQAMgMAQAAIAAAAQARAAALAMIAAAAQAMAMAAAQIAAAAQAAARgMALIAAAAQgLAMgRAAIAAAAQgLAAgJgFIAAAAQAUAWAAAdIAAAAQAAAigYAXIAAAAQgXAYghAAIAAAAQghAAgXgYg");
	var mask_graphics_1 = new cjs.Graphics().p("AixD5QhJhJAAhoIAAAAQAAhbA7hEIAAAAQgaANgfAAIAAAAQg0AAgkgkIAAAAQgkgkAAgzIAAAAQAAg0AkgkIAAAAQAkgkA0AAIAAAAQAzAAAkAkIAAAAQAkAkAAA0IAAAAQAAAkgTAeIAAAAQA/gtBRAAIAAAAQBTAABAAwIAAAAQgVgeAAgnIAAAAQAAg0AkgkIAAAAQAkgkAzAAIAAAAQA0AAAkAkIAAAAQAkAkAAA0IAAAAQAAAzgkAkIAAAAQgkAkg0AAIAAAAQgiAAgbgQIAAAAQA9BFAABdIAAAAQAABohKBJIAAAAQhJBJhmAAIAAAAQhoAAhJhJg");
	var mask_graphics_2 = new cjs.Graphics().p("AkpGiQh7h7AAitIAAAAQAAiaBihzIAAAAQgrAXg1AAIAAAAQhWAAg9g9IAAAAQg9g9AAhWIAAAAQAAhWA9g9IAAAAQA9g9BWAAIAAAAQBWAAA9A9IAAAAQA9A9AABWIAAAAQAAA+ggAxIAAAAQBphMCIAAIAAAAQCMAABrBRIAAAAQgjgzAAhBIAAAAQAAhWA9g9IAAAAQA9g9BWAAIAAAAQBWAAA9A9IAAAAQA9A9AABWIAAAAQAABWg9A9IAAAAQg9A9hWAAIAAAAQg5AAgugbIAAAAQBlB0AACdIAAAAQAACth7B7IAAAAQh6B7itAAIAAAAQitAAh7h7g");
	var mask_graphics_3 = new cjs.Graphics().p("AmiJLQisisAAj0IAAAAQAAjZCJihIAAAAQg8AghKAAIAAAAQh5AAhVhVIAAAAQhWhWAAh5IAAAAQAAh4BWhWIAAAAQBVhVB5AAIAAAAQB5AABVBVIAAAAQBWBWAAB4IAAAAQAABXgtBFIAAAAQCUhqC+AAIAAAAQDFAACXByIAAAAQgyhIAAhcIAAAAQAAh4BWhWIAAAAQBVhVB5AAIAAAAQB5AABVBVIAAAAQBWBWAAB4IAAAAQAAB5hWBWIAAAAQhVBVh5AAIAAAAQhQAAhBgmIAAAAQCPCjAADdIAAAAQAAD0itCsIAAAAQisCsjzAAIAAAAQjzAAitisg");
	var mask_graphics_4 = new cjs.Graphics().p("AobL0QjdjeAAk6IAAAAQAAkXCxjQIAAAAQhOAphfAAIAAAAQicAAhuhuIAAAAQhuhuAAibIAAAAQAAicBuhuIAAAAQBuhuCcAAIAAAAQCbAABuBuIAAAAQBuBuAACcIAAAAQAABwg5BYIAAAAQC+iID2AAIAAAAQD9AADCCSIAAAAQg/hcAAh2IAAAAQAAicBuhuIAAAAQBuhuCbAAIAAAAQCcAABuBuIAAAAQBuBuAACcIAAAAQAACbhuBuIAAAAQhuBuicAAIAAAAQhnAAhTgwIAAAAQC4DRAAEdIAAAAQAAE6jfDeIAAAAQjeDek4AAIAAAAQk6AAjfjeg");
	var mask_graphics_5 = new cjs.Graphics().p("AqTOdQkQkQAAmAIAAAAQAAlWDZj+IAAAAQhfAzh1AAIAAAAQi+AAiHiHIAAAAQiGiHAAi+IAAAAQAAi+CGiHIAAAAQCHiHC+AAIAAAAQC/AACGCHIAAAAQCHCHAAC+IAAAAQAACJhGBsIAAAAQDoimEtAAIAAAAQE2AADuCyIAAAAQhOhwAAiRIAAAAQAAi+CHiHIAAAAQCGiHC/AAIAAAAQC+AACHCHIAAAAQCGCHAAC+IAAAAQAAC+iGCHIAAAAQiHCHi+AAIAAAAQh/AAhmg8IAAAAQDhEBAAFcIAAAAQAAGAkQEQIAAAAQkPEQl/AAIAAAAQmAAAkQkQg");
	var mask_graphics_6 = new cjs.Graphics().p("AsMRGQlBlBAAnHIAAAAQAAmVEAkrIAAAAQhwA7iKAAIAAAAQjhAAififIAAAAQigifAAjiIAAAAQAAjhCgifIAAAAQCfifDhAAIAAAAQDhAACfCfIAAAAQCgCfAADhIAAAAQAACihTCAIAAAAQESjFFkAAIAAAAQFwAAEZDUIAAAAQhdiFAAisIAAAAQAAjhCgifIAAAAQCfifDhAAIAAAAQDhAACfCfIAAAAQCgCfAADhIAAAAQAADiigCfIAAAAQifCfjhAAIAAAAQiWAAh4hGIAAAAQEKEvAAGcIAAAAQAAHHlCFBIAAAAQlBFBnFAAIAAAAQnGAAlClBg");
	var mask_graphics_7 = new cjs.Graphics().p("AuETvQlzlzAAoMIAAAAQAAnUEolaIAAAAQiDBEieAAIAAAAQkEAAi4i3IAAAAQi4i4AAkEIAAAAQAAkEC4i4IAAAAQC4i4EEAAIAAAAQEEAAC3C4IAAAAQC4C4AAEEIAAAAQAAC7hfCTIAAAAQE9jjGaAAIAAAAQGpAAFED0IAAAAQhqiZAAjGIAAAAQAAkEC4i4IAAAAQC3i4EEAAIAAAAQEEAAC4C4IAAAAQC4C4AAEEIAAAAQAAEEi4C4IAAAAQi4C3kEAAIAAAAQisAAiMhRIAAAAQE0FeAAHdIAAAAQAAIMl0FzIAAAAQlyFzoMAAIAAAAQoMAAlzlzg");
	var mask_graphics_8 = new cjs.Graphics().p("Av9WYQmkmlAApSIAAAAQAAoTFPmIIAAAAQiUBOi0AAIAAAAQkmAAjRjRIAAAAQjQjQAAknIAAAAQAAknDQjQIAAAAQDRjQEmAAIAAAAQEnAADQDQIAAAAQDRDQAAEnIAAAAQAADUhsCnIAAAAQFnkBHSAAIAAAAQHhAAFwEVIAAAAQh5ivAAjgIAAAAQAAknDRjQIAAAAQDQjQEnAAIAAAAQEmAADRDQIAAAAQDQDQAAEnIAAAAQAAEnjQDQIAAAAQjRDRkmAAIAAAAQjEAAiehcIAAAAQFcGNAAIcIAAAAQAAJSmlGlIAAAAQmkGkpRAAIAAAAQpTAAmlmkg");
	var mask_graphics_9 = new cjs.Graphics().p("Ax1ZAQnXnWAAqYIAAAAQAApRF4m3IAAAAQimBXjJAAIAAAAQlKAAjojpIAAAAQjpjpAAlJIAAAAQAAlKDpjpIAAAAQDojpFKAAIAAAAQFKAADpDpIAAAAQDpDpAAFKIAAAAQAADth5C7IAAAAQGRkgIJAAIAAAAQIaAAGbE1IAAAAQiHjDAAj6IAAAAQAAlKDpjpIAAAAQDqjpFJAAIAAAAQFKAADoDpIAAAAQDqDpgBFKIAAAAQABFJjqDpIAAAAQjoDplKAAIAAAAQjbAAiwhnIAAAAQGFG8AAJcIAAAAQAAKYnWHWIAAAAQnWHXqYAAIAAAAQqZAAnWnXg");
	var mask_graphics_49 = new cjs.Graphics().p("Ax1ZAQnXnWAAqYIAAAAQAApRF4m3IAAAAQimBXjJAAIAAAAQlKAAjojpIAAAAQjpjpAAlJIAAAAQAAlKDpjpIAAAAQDojpFKAAIAAAAQFKAADpDpIAAAAQDpDpAAFKIAAAAQAADth5C7IAAAAQGRkgIJAAIAAAAQIaAAGbE1IAAAAQiHjDAAj6IAAAAQAAlKDpjpIAAAAQDqjpFJAAIAAAAQFKAADoDpIAAAAQDqDpgBFKIAAAAQABFJjqDpIAAAAQjoDplKAAIAAAAQjbAAiwhnIAAAAQGFG8AAJcIAAAAQAAKYnWHWIAAAAQnWHXqYAAIAAAAQqZAAnWnXg");
	var mask_graphics_50 = new cjs.Graphics().p("AwJWoQmpmpAApZIAAAAQAAoZFTmNIAAAAQiVBPi3AAIAAAAQkqAAjTjTIAAAAQjTjTAAkqIAAAAQAAkrDTjSIAAAAQDTjTEqAAIAAAAQErAADSDTIAAAAQDTDSAAErIAAAAQAADWhtCpIAAAAQFrkEHYAAIAAAAQHnAAF0EYIAAAAQh6iwAAjjIAAAAQAAkrDTjSIAAAAQDSjTErAAIAAAAQEqAADTDTIAAAAQDTDSAAErIAAAAQAAEqjTDTIAAAAQjTDTkqAAIAAAAQjHAAifheIAAAAQFgGSAAIjIAAAAQAAJZmqGpIAAAAQmpGqpYAAIAAAAQpaAAmqmqg");
	var mask_graphics_51 = new cjs.Graphics().p("AucUQQl9l8AAobIAAAAQAAngEwljIAAAAQiGBGijAAIAAAAQkLAAi9i9IAAAAQi9i8AAkLIAAAAQAAkLC9i9IAAAAQC9i9ELAAIAAAAQELAAC8C9IAAAAQC9C9AAELIAAAAQAADAhiCXIAAAAQFGjpGlAAIAAAAQG0AAFND7IAAAAQhtieAAjLIAAAAQAAkLC9i9IAAAAQC8i9ELAAIAAAAQELAAC9C9IAAAAQC9C9AAELIAAAAQAAELi9C8IAAAAQi9C9kLAAIAAAAQixAAiPhTIAAAAQE7FnAAHpIAAAAQAAIbl9F8IAAAAQl8F+oaAAIAAAAQoaAAl9l+g");
	var mask_graphics_52 = new cjs.Graphics().p("AswR4QlQlQAAnbIAAAAQAAmoEMk5IAAAAQh2A+iQAAIAAAAQjrAAininIAAAAQinimAAjsIAAAAQAAjsCnimIAAAAQCninDrAAIAAAAQDsAACmCnIAAAAQCnCmAADsIAAAAQAACphWCGIAAAAQEfjOF0AAIAAAAQGBAAElDeIAAAAQhgiMAAizIAAAAQAAjsCnimIAAAAQCminDsAAIAAAAQDrAACnCnIAAAAQCnCmAADsIAAAAQAADsinCmIAAAAQinCnjrAAIAAAAQidAAh+hKIAAAAQEXE+AAGvIAAAAQAAHblRFQIAAAAQlQFRnaAAIAAAAQnbAAlRlRg");
	var mask_graphics_53 = new cjs.Graphics().p("ArDPgQkkkjAAmcIAAAAQAAlvDpkRIAAAAQhnA2h8AAIAAAAQjNAAiQiQIAAAAQiRiRAAjMIAAAAQAAjMCRiRIAAAAQCQiQDNAAIAAAAQDMAACQCQIAAAAQCRCRAADMIAAAAQAACThLB0IAAAAQD5iyFDAAIAAAAQFNAAD/C/IAAAAQhUh4AAicIAAAAQAAjMCRiRIAAAAQCQiQDMAAIAAAAQDNAACQCQIAAAAQCRCRAADMIAAAAQAADMiRCRIAAAAQiQCQjNAAIAAAAQiHAAhug/IAAAAQDyETAAF2IAAAAQAAGckkEjIAAAAQkjEkmbAAIAAAAQmdAAkjkkg");
	var mask_graphics_54 = new cjs.Graphics().p("ApXNIQj3j2AAldIAAAAQAAk3DFjnIAAAAQhWAuhqAAIAAAAQitAAh6h6IAAAAQh7h7AAitIAAAAQAAitB7h6IAAAAQB6h6CtAAIAAAAQCtAAB6B6IAAAAQB7B6AACtIAAAAQAAB9hABiIAAAAQDTiXERAAIAAAAQEaAADYCiIAAAAQhHhmAAiEIAAAAQAAitB7h6IAAAAQB6h6CtAAIAAAAQCtAAB6B6IAAAAQB7B6AACtIAAAAQAACth7B7IAAAAQh6B6itAAIAAAAQhzAAhcg2IAAAAQDMDpAAE9IAAAAQAAFdj3D2IAAAAQj3D3lcAAIAAAAQldAAj3j3g");
	var mask_graphics_55 = new cjs.Graphics().p("AnqKwQjKjKAAkeIAAAAQAAj+Chi9IAAAAQhHAmhXAAIAAAAQiNAAhlhlIAAAAQhkhkAAiNIAAAAQAAiOBkhkIAAAAQBlhlCNAAIAAAAQCOAABkBlIAAAAQBkBkAACOIAAAAQAABlgzBRIAAAAQCsh8DgAAIAAAAQDnAACxCFIAAAAQg6hUAAhrIAAAAQAAiOBkhkIAAAAQBkhlCOAAIAAAAQCNAABlBlIAAAAQBkBkAACOIAAAAQAACNhkBkIAAAAQhlBliNAAIAAAAQheAAhMgtIAAAAQCnC/AAEDIAAAAQAAEejKDKIAAAAQjKDLkdAAIAAAAQkeAAjKjLg");
	var mask_graphics_56 = new cjs.Graphics().p("Al+IYQididAAjfIAAAAQAAjGB9iTIAAAAQg3AdhDAAIAAAAQhvAAhOhOIAAAAQhOhOAAhuIAAAAQAAhvBOhOIAAAAQBOhOBvAAIAAAAQBuAABOBOIAAAAQBOBOAABvIAAAAQAABPgoA/IAAAAQCGhhCvAAIAAAAQCzAACKBoIAAAAQgthBAAhUIAAAAQAAhvBOhOIAAAAQBOhOBuAAIAAAAQBvAABOBOIAAAAQBOBOAABvIAAAAQAABuhOBOIAAAAQhOBOhvAAIAAAAQhJAAg7giIAAAAQCCCUAADKIAAAAQAADfidCdIAAAAQieCejdAAIAAAAQjfAAieieg");
	var mask_graphics_57 = new cjs.Graphics().p("AkRGAQhxhxAAifIAAAAQAAiOBahpIAAAAQgoAVgwAAIAAAAQhPAAg4g4IAAAAQg4g4AAhPIAAAAQAAhPA4g4IAAAAQA4g4BPAAIAAAAQBPAAA4A4IAAAAQA4A4AABPIAAAAQAAA5gdAtIAAAAQBghFB9AAIAAAAQCBAABiBKIAAAAQgggvAAg8IAAAAQAAhPA4g4IAAAAQA4g4BPAAIAAAAQBPAAA4A4IAAAAQA4A4AABPIAAAAQAABPg4A4IAAAAQg4A4hPAAIAAAAQg1AAgqgZIAAAAQBeBrgBCQIAAAAQAACfhwBxIAAAAQhxBxifAAIAAAAQifAAhxhxg");
	var mask_graphics_58 = new cjs.Graphics().p("AilDoQhEhEAAhgIAAAAQAAhWA3g/IAAAAQgYAMgeAAIAAAAQgvAAgighIAAAAQgigiAAgwIAAAAQAAgwAighIAAAAQAigiAvAAIAAAAQAwAAAiAiIAAAAQAiAhAAAwIAAAAQAAAigSAcIAAAAQA6gqBMAAIAAAAQBNAAA8AtIAAAAQgUgdAAgkIAAAAQAAgwAighIAAAAQAigiAwAAIAAAAQAvAAAiAiIAAAAQAiAhAAAwIAAAAQAAAwgiAiIAAAAQgiAhgvAAIAAAAQggAAgagPIAAAAQA5BBAABXIAAAAQAABghFBEIAAAAQhEBEhfAAIAAAAQhgAAhFhEg");
	var mask_graphics_59 = new cjs.Graphics().p("Ag4BQQgYgXAAgiIAAAAQAAgcATgWIAAAAQgIAEgKAAIAAAAQgRAAgLgMIAAAAQgMgLAAgRIAAAAQAAgQAMgMIAAAAQALgMARAAIAAAAQAQAAAMAMIAAAAQAMAMAAAQIAAAAQAAAMgGAJIAAAAQAUgOAZAAIAAAAQAbAAAUAQIAAAAQgHgKAAgNIAAAAQAAgQAMgMIAAAAQAMgMAQAAIAAAAQARAAALAMIAAAAQAMAMAAAQIAAAAQAAARgMALIAAAAQgLAMgRAAIAAAAQgLAAgJgFIAAAAQAUAWAAAdIAAAAQAAAigYAXIAAAAQgXAYghAAIAAAAQghAAgXgYg");
	var mask_graphics_60 = new cjs.Graphics().p("Ag4BQQgYgXAAgiIAAAAQAAgcATgWIAAAAQgIAEgKAAIAAAAQgRAAgLgMIAAAAQgMgLAAgRIAAAAQAAgQAMgMIAAAAQALgMARAAIAAAAQAQAAAMAMIAAAAQAMAMAAAQIAAAAQAAAMgGAJIAAAAQAUgOAZAAIAAAAQAbAAAUAQIAAAAQgHgKAAgNIAAAAQAAgQAMgMIAAAAQAMgMAQAAIAAAAQARAAALAMIAAAAQAMAMAAAQIAAAAQAAARgMALIAAAAQgLAMgRAAIAAAAQgLAAgJgFIAAAAQAUAWAAAdIAAAAQAAAigYAXIAAAAQgXAYghAAIAAAAQghAAgXgYg");
	var mask_graphics_61 = new cjs.Graphics().p("AixD5QhJhJAAhoIAAAAQAAhbA7hEIAAAAQgaANgfAAIAAAAQg0AAgkgkIAAAAQgkgkAAgzIAAAAQAAg0AkgkIAAAAQAkgkA0AAIAAAAQAzAAAkAkIAAAAQAkAkAAA0IAAAAQAAAkgTAeIAAAAQA/gtBRAAIAAAAQBTAABAAwIAAAAQgVgeAAgnIAAAAQAAg0AkgkIAAAAQAkgkAzAAIAAAAQA0AAAkAkIAAAAQAkAkAAA0IAAAAQAAAzgkAkIAAAAQgkAkg0AAIAAAAQgiAAgbgQIAAAAQA9BFAABdIAAAAQAABohKBJIAAAAQhJBJhmAAIAAAAQhoAAhJhJg");
	var mask_graphics_62 = new cjs.Graphics().p("AkpGiQh7h7AAitIAAAAQAAiaBihzIAAAAQgrAXg1AAIAAAAQhWAAg9g9IAAAAQg9g9AAhWIAAAAQAAhWA9g9IAAAAQA9g9BWAAIAAAAQBWAAA9A9IAAAAQA9A9AABWIAAAAQAAA+ggAxIAAAAQBphMCIAAIAAAAQCMAABrBRIAAAAQgjgzAAhBIAAAAQAAhWA9g9IAAAAQA9g9BWAAIAAAAQBWAAA9A9IAAAAQA9A9AABWIAAAAQAABWg9A9IAAAAQg9A9hWAAIAAAAQg5AAgugbIAAAAQBlB0AACdIAAAAQAACth7B7IAAAAQh6B7itAAIAAAAQitAAh7h7g");
	var mask_graphics_63 = new cjs.Graphics().p("AmiJLQisisAAj0IAAAAQAAjZCJihIAAAAQg8AghKAAIAAAAQh5AAhVhVIAAAAQhWhWAAh5IAAAAQAAh4BWhWIAAAAQBVhVB5AAIAAAAQB5AABVBVIAAAAQBWBWAAB4IAAAAQAABXgtBFIAAAAQCUhqC+AAIAAAAQDFAACXByIAAAAQgyhIAAhcIAAAAQAAh4BWhWIAAAAQBVhVB5AAIAAAAQB5AABVBVIAAAAQBWBWAAB4IAAAAQAAB5hWBWIAAAAQhVBVh5AAIAAAAQhQAAhBgmIAAAAQCPCjAADdIAAAAQAAD0itCsIAAAAQisCsjzAAIAAAAQjzAAitisg");
	var mask_graphics_64 = new cjs.Graphics().p("AobL0QjdjeAAk6IAAAAQAAkXCxjQIAAAAQhOAphfAAIAAAAQicAAhuhuIAAAAQhuhuAAibIAAAAQAAicBuhuIAAAAQBuhuCcAAIAAAAQCbAABuBuIAAAAQBuBuAACcIAAAAQAABwg5BYIAAAAQC+iID2AAIAAAAQD9AADCCSIAAAAQg/hcAAh2IAAAAQAAicBuhuIAAAAQBuhuCbAAIAAAAQCcAABuBuIAAAAQBuBuAACcIAAAAQAACbhuBuIAAAAQhuBuicAAIAAAAQhnAAhTgwIAAAAQC4DRAAEdIAAAAQAAE6jfDeIAAAAQjeDek4AAIAAAAQk6AAjfjeg");
	var mask_graphics_65 = new cjs.Graphics().p("AqTOdQkQkQAAmAIAAAAQAAlWDZj+IAAAAQhfAzh1AAIAAAAQi+AAiHiHIAAAAQiGiHAAi+IAAAAQAAi+CGiHIAAAAQCHiHC+AAIAAAAQC/AACGCHIAAAAQCHCHAAC+IAAAAQAACJhGBsIAAAAQDoimEtAAIAAAAQE2AADuCyIAAAAQhOhwAAiRIAAAAQAAi+CHiHIAAAAQCGiHC/AAIAAAAQC+AACHCHIAAAAQCGCHAAC+IAAAAQAAC+iGCHIAAAAQiHCHi+AAIAAAAQh/AAhmg8IAAAAQDhEBAAFcIAAAAQAAGAkQEQIAAAAQkPEQl/AAIAAAAQmAAAkQkQg");
	var mask_graphics_66 = new cjs.Graphics().p("AsMRGQlBlBAAnHIAAAAQAAmVEAkrIAAAAQhwA7iKAAIAAAAQjhAAififIAAAAQigifAAjiIAAAAQAAjhCgifIAAAAQCfifDhAAIAAAAQDhAACfCfIAAAAQCgCfAADhIAAAAQAACihTCAIAAAAQESjFFkAAIAAAAQFwAAEZDUIAAAAQhdiFAAisIAAAAQAAjhCgifIAAAAQCfifDhAAIAAAAQDhAACfCfIAAAAQCgCfAADhIAAAAQAADiigCfIAAAAQifCfjhAAIAAAAQiWAAh4hGIAAAAQEKEvAAGcIAAAAQAAHHlCFBIAAAAQlBFBnFAAIAAAAQnGAAlClBg");
	var mask_graphics_67 = new cjs.Graphics().p("AuETvQlzlzAAoMIAAAAQAAnUEolaIAAAAQiDBEieAAIAAAAQkEAAi4i3IAAAAQi4i4AAkEIAAAAQAAkEC4i4IAAAAQC4i4EEAAIAAAAQEEAAC3C4IAAAAQC4C4AAEEIAAAAQAAC7hfCTIAAAAQE9jjGaAAIAAAAQGpAAFED0IAAAAQhqiZAAjGIAAAAQAAkEC4i4IAAAAQC3i4EEAAIAAAAQEEAAC4C4IAAAAQC4C4AAEEIAAAAQAAEEi4C4IAAAAQi4C3kEAAIAAAAQisAAiMhRIAAAAQE0FeAAHdIAAAAQAAIMl0FzIAAAAQlyFzoMAAIAAAAQoMAAlzlzg");
	var mask_graphics_68 = new cjs.Graphics().p("Av9WYQmkmlAApSIAAAAQAAoTFPmIIAAAAQiUBOi0AAIAAAAQkmAAjRjRIAAAAQjQjQAAknIAAAAQAAknDQjQIAAAAQDRjQEmAAIAAAAQEnAADQDQIAAAAQDRDQAAEnIAAAAQAADUhsCnIAAAAQFnkBHSAAIAAAAQHhAAFwEVIAAAAQh5ivAAjgIAAAAQAAknDRjQIAAAAQDQjQEnAAIAAAAQEmAADRDQIAAAAQDQDQAAEnIAAAAQAAEnjQDQIAAAAQjRDRkmAAIAAAAQjEAAiehcIAAAAQFcGNAAIcIAAAAQAAJSmlGlIAAAAQmkGkpRAAIAAAAQpTAAmlmkg");
	var mask_graphics_69 = new cjs.Graphics().p("Ax1ZAQnXnWAAqYIAAAAQAApRF4m3IAAAAQimBXjJAAIAAAAQlKAAjojpIAAAAQjpjpAAlJIAAAAQAAlKDpjpIAAAAQDojpFKAAIAAAAQFKAADpDpIAAAAQDpDpAAFKIAAAAQAADth5C7IAAAAQGRkgIJAAIAAAAQIaAAGbE1IAAAAQiHjDAAj6IAAAAQAAlKDpjpIAAAAQDqjpFJAAIAAAAQFKAADoDpIAAAAQDqDpgBFKIAAAAQABFJjqDpIAAAAQjoDplKAAIAAAAQjbAAiwhnIAAAAQGFG8AAJcIAAAAQAAKYnWHWIAAAAQnWHXqYAAIAAAAQqZAAnWnXg");
	var mask_graphics_109 = new cjs.Graphics().p("Ax1ZAQnXnWAAqYIAAAAQAApRF4m3IAAAAQimBXjJAAIAAAAQlKAAjojpIAAAAQjpjpAAlJIAAAAQAAlKDpjpIAAAAQDojpFKAAIAAAAQFKAADpDpIAAAAQDpDpAAFKIAAAAQAADth5C7IAAAAQGRkgIJAAIAAAAQIaAAGbE1IAAAAQiHjDAAj6IAAAAQAAlKDpjpIAAAAQDqjpFJAAIAAAAQFKAADoDpIAAAAQDqDpgBFKIAAAAQABFJjqDpIAAAAQjoDplKAAIAAAAQjbAAiwhnIAAAAQGFG8AAJcIAAAAQAAKYnWHWIAAAAQnWHXqYAAIAAAAQqZAAnWnXg");
	var mask_graphics_110 = new cjs.Graphics().p("AwJWoQmpmpAApZIAAAAQAAoZFTmNIAAAAQiVBPi3AAIAAAAQkqAAjTjTIAAAAQjTjTAAkqIAAAAQAAkrDTjSIAAAAQDTjTEqAAIAAAAQErAADSDTIAAAAQDTDSAAErIAAAAQAADWhtCpIAAAAQFrkEHYAAIAAAAQHnAAF0EYIAAAAQh6iwAAjjIAAAAQAAkrDTjSIAAAAQDSjTErAAIAAAAQEqAADTDTIAAAAQDTDSAAErIAAAAQAAEqjTDTIAAAAQjTDTkqAAIAAAAQjHAAifheIAAAAQFgGSAAIjIAAAAQAAJZmqGpIAAAAQmpGqpYAAIAAAAQpaAAmqmqg");
	var mask_graphics_111 = new cjs.Graphics().p("AucUQQl9l8AAobIAAAAQAAngEwljIAAAAQiGBGijAAIAAAAQkLAAi9i9IAAAAQi9i8AAkLIAAAAQAAkLC9i9IAAAAQC9i9ELAAIAAAAQELAAC8C9IAAAAQC9C9AAELIAAAAQAADAhiCXIAAAAQFGjpGlAAIAAAAQG0AAFND7IAAAAQhtieAAjLIAAAAQAAkLC9i9IAAAAQC8i9ELAAIAAAAQELAAC9C9IAAAAQC9C9AAELIAAAAQAAELi9C8IAAAAQi9C9kLAAIAAAAQixAAiPhTIAAAAQE7FnAAHpIAAAAQAAIbl9F8IAAAAQl8F+oaAAIAAAAQoaAAl9l+g");
	var mask_graphics_112 = new cjs.Graphics().p("AswR4QlQlQAAnbIAAAAQAAmoEMk5IAAAAQh2A+iQAAIAAAAQjrAAininIAAAAQinimAAjsIAAAAQAAjsCnimIAAAAQCninDrAAIAAAAQDsAACmCnIAAAAQCnCmAADsIAAAAQAACphWCGIAAAAQEfjOF0AAIAAAAQGBAAElDeIAAAAQhgiMAAizIAAAAQAAjsCnimIAAAAQCminDsAAIAAAAQDrAACnCnIAAAAQCnCmAADsIAAAAQAADsinCmIAAAAQinCnjrAAIAAAAQidAAh+hKIAAAAQEXE+AAGvIAAAAQAAHblRFQIAAAAQlQFRnaAAIAAAAQnbAAlRlRg");
	var mask_graphics_113 = new cjs.Graphics().p("ArDPgQkkkjAAmcIAAAAQAAlvDpkRIAAAAQhnA2h8AAIAAAAQjNAAiQiQIAAAAQiRiRAAjMIAAAAQAAjMCRiRIAAAAQCQiQDNAAIAAAAQDMAACQCQIAAAAQCRCRAADMIAAAAQAACThLB0IAAAAQD5iyFDAAIAAAAQFNAAD/C/IAAAAQhUh4AAicIAAAAQAAjMCRiRIAAAAQCQiQDMAAIAAAAQDNAACQCQIAAAAQCRCRAADMIAAAAQAADMiRCRIAAAAQiQCQjNAAIAAAAQiHAAhug/IAAAAQDyETAAF2IAAAAQAAGckkEjIAAAAQkjEkmbAAIAAAAQmdAAkjkkg");
	var mask_graphics_114 = new cjs.Graphics().p("ApXNIQj3j2AAldIAAAAQAAk3DFjnIAAAAQhWAuhqAAIAAAAQitAAh6h6IAAAAQh7h7AAitIAAAAQAAitB7h6IAAAAQB6h6CtAAIAAAAQCtAAB6B6IAAAAQB7B6AACtIAAAAQAAB9hABiIAAAAQDTiXERAAIAAAAQEaAADYCiIAAAAQhHhmAAiEIAAAAQAAitB7h6IAAAAQB6h6CtAAIAAAAQCtAAB6B6IAAAAQB7B6AACtIAAAAQAACth7B7IAAAAQh6B6itAAIAAAAQhzAAhcg2IAAAAQDMDpAAE9IAAAAQAAFdj3D2IAAAAQj3D3lcAAIAAAAQldAAj3j3g");
	var mask_graphics_115 = new cjs.Graphics().p("AnqKwQjKjKAAkeIAAAAQAAj+Chi9IAAAAQhHAmhXAAIAAAAQiNAAhlhlIAAAAQhkhkAAiNIAAAAQAAiOBkhkIAAAAQBlhlCNAAIAAAAQCOAABkBlIAAAAQBkBkAACOIAAAAQAABlgzBRIAAAAQCsh8DgAAIAAAAQDnAACxCFIAAAAQg6hUAAhrIAAAAQAAiOBkhkIAAAAQBkhlCOAAIAAAAQCNAABlBlIAAAAQBkBkAACOIAAAAQAACNhkBkIAAAAQhlBliNAAIAAAAQheAAhMgtIAAAAQCnC/AAEDIAAAAQAAEejKDKIAAAAQjKDLkdAAIAAAAQkeAAjKjLg");
	var mask_graphics_116 = new cjs.Graphics().p("Al+IYQididAAjfIAAAAQAAjGB9iTIAAAAQg3AdhDAAIAAAAQhvAAhOhOIAAAAQhOhOAAhuIAAAAQAAhvBOhOIAAAAQBOhOBvAAIAAAAQBuAABOBOIAAAAQBOBOAABvIAAAAQAABPgoA/IAAAAQCGhhCvAAIAAAAQCzAACKBoIAAAAQgthBAAhUIAAAAQAAhvBOhOIAAAAQBOhOBuAAIAAAAQBvAABOBOIAAAAQBOBOAABvIAAAAQAABuhOBOIAAAAQhOBOhvAAIAAAAQhJAAg7giIAAAAQCCCUAADKIAAAAQAADfidCdIAAAAQieCejdAAIAAAAQjfAAieieg");
	var mask_graphics_117 = new cjs.Graphics().p("AkRGAQhxhxAAifIAAAAQAAiOBahpIAAAAQgoAVgwAAIAAAAQhPAAg4g4IAAAAQg4g4AAhPIAAAAQAAhPA4g4IAAAAQA4g4BPAAIAAAAQBPAAA4A4IAAAAQA4A4AABPIAAAAQAAA5gdAtIAAAAQBghFB9AAIAAAAQCBAABiBKIAAAAQgggvAAg8IAAAAQAAhPA4g4IAAAAQA4g4BPAAIAAAAQBPAAA4A4IAAAAQA4A4AABPIAAAAQAABPg4A4IAAAAQg4A4hPAAIAAAAQg1AAgqgZIAAAAQBeBrgBCQIAAAAQAACfhwBxIAAAAQhxBxifAAIAAAAQifAAhxhxg");
	var mask_graphics_118 = new cjs.Graphics().p("AilDoQhEhEAAhgIAAAAQAAhWA3g/IAAAAQgYAMgeAAIAAAAQgvAAgighIAAAAQgigiAAgwIAAAAQAAgwAighIAAAAQAigiAvAAIAAAAQAwAAAiAiIAAAAQAiAhAAAwIAAAAQAAAigSAcIAAAAQA6gqBMAAIAAAAQBNAAA8AtIAAAAQgUgdAAgkIAAAAQAAgwAighIAAAAQAigiAwAAIAAAAQAvAAAiAiIAAAAQAiAhAAAwIAAAAQAAAwgiAiIAAAAQgiAhgvAAIAAAAQggAAgagPIAAAAQA5BBAABXIAAAAQAABghFBEIAAAAQhEBEhfAAIAAAAQhgAAhFhEg");
	var mask_graphics_119 = new cjs.Graphics().p("Ag4BQQgYgXAAgiIAAAAQAAgcATgWIAAAAQgIAEgKAAIAAAAQgRAAgLgMIAAAAQgMgLAAgRIAAAAQAAgQAMgMIAAAAQALgMARAAIAAAAQAQAAAMAMIAAAAQAMAMAAAQIAAAAQAAAMgGAJIAAAAQAUgOAZAAIAAAAQAbAAAUAQIAAAAQgHgKAAgNIAAAAQAAgQAMgMIAAAAQAMgMAQAAIAAAAQARAAALAMIAAAAQAMAMAAAQIAAAAQAAARgMALIAAAAQgLAMgRAAIAAAAQgLAAgJgFIAAAAQAUAWAAAdIAAAAQAAAigYAXIAAAAQgXAYghAAIAAAAQghAAgXgYg");
	var mask_graphics_120 = new cjs.Graphics().p("Ag4BQQgYgXAAgiIAAAAQAAgcATgWIAAAAQgIAEgKAAIAAAAQgRAAgLgMIAAAAQgMgLAAgRIAAAAQAAgQAMgMIAAAAQALgMARAAIAAAAQAQAAAMAMIAAAAQAMAMAAAQIAAAAQAAAMgGAJIAAAAQAUgOAZAAIAAAAQAbAAAUAQIAAAAQgHgKAAgNIAAAAQAAgQAMgMIAAAAQAMgMAQAAIAAAAQARAAALAMIAAAAQAMAMAAAQIAAAAQAAARgMALIAAAAQgLAMgRAAIAAAAQgLAAgJgFIAAAAQAUAWAAAdIAAAAQAAAigYAXIAAAAQgXAYghAAIAAAAQghAAgXgYg");
	var mask_graphics_121 = new cjs.Graphics().p("AixD5QhJhJAAhoIAAAAQAAhbA7hEIAAAAQgaANgfAAIAAAAQg0AAgkgkIAAAAQgkgkAAgzIAAAAQAAg0AkgkIAAAAQAkgkA0AAIAAAAQAzAAAkAkIAAAAQAkAkAAA0IAAAAQAAAkgTAeIAAAAQA/gtBRAAIAAAAQBTAABAAwIAAAAQgVgeAAgnIAAAAQAAg0AkgkIAAAAQAkgkAzAAIAAAAQA0AAAkAkIAAAAQAkAkAAA0IAAAAQAAAzgkAkIAAAAQgkAkg0AAIAAAAQgiAAgbgQIAAAAQA9BFAABdIAAAAQAABohKBJIAAAAQhJBJhmAAIAAAAQhoAAhJhJg");
	var mask_graphics_122 = new cjs.Graphics().p("AkpGiQh7h7AAitIAAAAQAAiaBihzIAAAAQgrAXg1AAIAAAAQhWAAg9g9IAAAAQg9g9AAhWIAAAAQAAhWA9g9IAAAAQA9g9BWAAIAAAAQBWAAA9A9IAAAAQA9A9AABWIAAAAQAAA+ggAxIAAAAQBphMCIAAIAAAAQCMAABrBRIAAAAQgjgzAAhBIAAAAQAAhWA9g9IAAAAQA9g9BWAAIAAAAQBWAAA9A9IAAAAQA9A9AABWIAAAAQAABWg9A9IAAAAQg9A9hWAAIAAAAQg5AAgugbIAAAAQBlB0AACdIAAAAQAACth7B7IAAAAQh6B7itAAIAAAAQitAAh7h7g");
	var mask_graphics_123 = new cjs.Graphics().p("AmiJLQisisAAj0IAAAAQAAjZCJihIAAAAQg8AghKAAIAAAAQh5AAhVhVIAAAAQhWhWAAh5IAAAAQAAh4BWhWIAAAAQBVhVB5AAIAAAAQB5AABVBVIAAAAQBWBWAAB4IAAAAQAABXgtBFIAAAAQCUhqC+AAIAAAAQDFAACXByIAAAAQgyhIAAhcIAAAAQAAh4BWhWIAAAAQBVhVB5AAIAAAAQB5AABVBVIAAAAQBWBWAAB4IAAAAQAAB5hWBWIAAAAQhVBVh5AAIAAAAQhQAAhBgmIAAAAQCPCjAADdIAAAAQAAD0itCsIAAAAQisCsjzAAIAAAAQjzAAitisg");
	var mask_graphics_124 = new cjs.Graphics().p("AobL0QjdjeAAk6IAAAAQAAkXCxjQIAAAAQhOAphfAAIAAAAQicAAhuhuIAAAAQhuhuAAibIAAAAQAAicBuhuIAAAAQBuhuCcAAIAAAAQCbAABuBuIAAAAQBuBuAACcIAAAAQAABwg5BYIAAAAQC+iID2AAIAAAAQD9AADCCSIAAAAQg/hcAAh2IAAAAQAAicBuhuIAAAAQBuhuCbAAIAAAAQCcAABuBuIAAAAQBuBuAACcIAAAAQAACbhuBuIAAAAQhuBuicAAIAAAAQhnAAhTgwIAAAAQC4DRAAEdIAAAAQAAE6jfDeIAAAAQjeDek4AAIAAAAQk6AAjfjeg");
	var mask_graphics_125 = new cjs.Graphics().p("AqTOdQkQkQAAmAIAAAAQAAlWDZj+IAAAAQhfAzh1AAIAAAAQi+AAiHiHIAAAAQiGiHAAi+IAAAAQAAi+CGiHIAAAAQCHiHC+AAIAAAAQC/AACGCHIAAAAQCHCHAAC+IAAAAQAACJhGBsIAAAAQDoimEtAAIAAAAQE2AADuCyIAAAAQhOhwAAiRIAAAAQAAi+CHiHIAAAAQCGiHC/AAIAAAAQC+AACHCHIAAAAQCGCHAAC+IAAAAQAAC+iGCHIAAAAQiHCHi+AAIAAAAQh/AAhmg8IAAAAQDhEBAAFcIAAAAQAAGAkQEQIAAAAQkPEQl/AAIAAAAQmAAAkQkQg");
	var mask_graphics_126 = new cjs.Graphics().p("AsMRGQlBlBAAnHIAAAAQAAmVEAkrIAAAAQhwA7iKAAIAAAAQjhAAififIAAAAQigifAAjiIAAAAQAAjhCgifIAAAAQCfifDhAAIAAAAQDhAACfCfIAAAAQCgCfAADhIAAAAQAACihTCAIAAAAQESjFFkAAIAAAAQFwAAEZDUIAAAAQhdiFAAisIAAAAQAAjhCgifIAAAAQCfifDhAAIAAAAQDhAACfCfIAAAAQCgCfAADhIAAAAQAADiigCfIAAAAQifCfjhAAIAAAAQiWAAh4hGIAAAAQEKEvAAGcIAAAAQAAHHlCFBIAAAAQlBFBnFAAIAAAAQnGAAlClBg");
	var mask_graphics_127 = new cjs.Graphics().p("AuETvQlzlzAAoMIAAAAQAAnUEolaIAAAAQiDBEieAAIAAAAQkEAAi4i3IAAAAQi4i4AAkEIAAAAQAAkEC4i4IAAAAQC4i4EEAAIAAAAQEEAAC3C4IAAAAQC4C4AAEEIAAAAQAAC7hfCTIAAAAQE9jjGaAAIAAAAQGpAAFED0IAAAAQhqiZAAjGIAAAAQAAkEC4i4IAAAAQC3i4EEAAIAAAAQEEAAC4C4IAAAAQC4C4AAEEIAAAAQAAEEi4C4IAAAAQi4C3kEAAIAAAAQisAAiMhRIAAAAQE0FeAAHdIAAAAQAAIMl0FzIAAAAQlyFzoMAAIAAAAQoMAAlzlzg");
	var mask_graphics_128 = new cjs.Graphics().p("Av9WYQmkmlAApSIAAAAQAAoTFPmIIAAAAQiUBOi0AAIAAAAQkmAAjRjRIAAAAQjQjQAAknIAAAAQAAknDQjQIAAAAQDRjQEmAAIAAAAQEnAADQDQIAAAAQDRDQAAEnIAAAAQAADUhsCnIAAAAQFnkBHSAAIAAAAQHhAAFwEVIAAAAQh5ivAAjgIAAAAQAAknDRjQIAAAAQDQjQEnAAIAAAAQEmAADRDQIAAAAQDQDQAAEnIAAAAQAAEnjQDQIAAAAQjRDRkmAAIAAAAQjEAAiehcIAAAAQFcGNAAIcIAAAAQAAJSmlGlIAAAAQmkGkpRAAIAAAAQpTAAmlmkg");
	var mask_graphics_129 = new cjs.Graphics().p("Ax1ZAQnXnWAAqYIAAAAQAApRF4m3IAAAAQimBXjJAAIAAAAQlKAAjojpIAAAAQjpjpAAlJIAAAAQAAlKDpjpIAAAAQDojpFKAAIAAAAQFKAADpDpIAAAAQDpDpAAFKIAAAAQAADth5C7IAAAAQGRkgIJAAIAAAAQIaAAGbE1IAAAAQiHjDAAj6IAAAAQAAlKDpjpIAAAAQDqjpFJAAIAAAAQFKAADoDpIAAAAQDqDpgBFKIAAAAQABFJjqDpIAAAAQjoDplKAAIAAAAQjbAAiwhnIAAAAQGFG8AAJcIAAAAQAAKYnWHWIAAAAQnWHXqYAAIAAAAQqZAAnWnXg");
	var mask_graphics_169 = new cjs.Graphics().p("Ax1ZAQnXnWAAqYIAAAAQAApRF4m3IAAAAQimBXjJAAIAAAAQlKAAjojpIAAAAQjpjpAAlJIAAAAQAAlKDpjpIAAAAQDojpFKAAIAAAAQFKAADpDpIAAAAQDpDpAAFKIAAAAQAADth5C7IAAAAQGRkgIJAAIAAAAQIaAAGbE1IAAAAQiHjDAAj6IAAAAQAAlKDpjpIAAAAQDqjpFJAAIAAAAQFKAADoDpIAAAAQDqDpgBFKIAAAAQABFJjqDpIAAAAQjoDplKAAIAAAAQjbAAiwhnIAAAAQGFG8AAJcIAAAAQAAKYnWHWIAAAAQnWHXqYAAIAAAAQqZAAnWnXg");
	var mask_graphics_170 = new cjs.Graphics().p("AwJWoQmpmpAApZIAAAAQAAoZFTmNIAAAAQiVBPi3AAIAAAAQkqAAjTjTIAAAAQjTjTAAkqIAAAAQAAkrDTjSIAAAAQDTjTEqAAIAAAAQErAADSDTIAAAAQDTDSAAErIAAAAQAADWhtCpIAAAAQFrkEHYAAIAAAAQHnAAF0EYIAAAAQh6iwAAjjIAAAAQAAkrDTjSIAAAAQDSjTErAAIAAAAQEqAADTDTIAAAAQDTDSAAErIAAAAQAAEqjTDTIAAAAQjTDTkqAAIAAAAQjHAAifheIAAAAQFgGSAAIjIAAAAQAAJZmqGpIAAAAQmpGqpYAAIAAAAQpaAAmqmqg");
	var mask_graphics_171 = new cjs.Graphics().p("AucUQQl9l8AAobIAAAAQAAngEwljIAAAAQiGBGijAAIAAAAQkLAAi9i9IAAAAQi9i8AAkLIAAAAQAAkLC9i9IAAAAQC9i9ELAAIAAAAQELAAC8C9IAAAAQC9C9AAELIAAAAQAADAhiCXIAAAAQFGjpGlAAIAAAAQG0AAFND7IAAAAQhtieAAjLIAAAAQAAkLC9i9IAAAAQC8i9ELAAIAAAAQELAAC9C9IAAAAQC9C9AAELIAAAAQAAELi9C8IAAAAQi9C9kLAAIAAAAQixAAiPhTIAAAAQE7FnAAHpIAAAAQAAIbl9F8IAAAAQl8F+oaAAIAAAAQoaAAl9l+g");
	var mask_graphics_172 = new cjs.Graphics().p("AswR4QlQlQAAnbIAAAAQAAmoEMk5IAAAAQh2A+iQAAIAAAAQjrAAininIAAAAQinimAAjsIAAAAQAAjsCnimIAAAAQCninDrAAIAAAAQDsAACmCnIAAAAQCnCmAADsIAAAAQAACphWCGIAAAAQEfjOF0AAIAAAAQGBAAElDeIAAAAQhgiMAAizIAAAAQAAjsCnimIAAAAQCminDsAAIAAAAQDrAACnCnIAAAAQCnCmAADsIAAAAQAADsinCmIAAAAQinCnjrAAIAAAAQidAAh+hKIAAAAQEXE+AAGvIAAAAQAAHblRFQIAAAAQlQFRnaAAIAAAAQnbAAlRlRg");
	var mask_graphics_173 = new cjs.Graphics().p("ArDPgQkkkjAAmcIAAAAQAAlvDpkRIAAAAQhnA2h8AAIAAAAQjNAAiQiQIAAAAQiRiRAAjMIAAAAQAAjMCRiRIAAAAQCQiQDNAAIAAAAQDMAACQCQIAAAAQCRCRAADMIAAAAQAACThLB0IAAAAQD5iyFDAAIAAAAQFNAAD/C/IAAAAQhUh4AAicIAAAAQAAjMCRiRIAAAAQCQiQDMAAIAAAAQDNAACQCQIAAAAQCRCRAADMIAAAAQAADMiRCRIAAAAQiQCQjNAAIAAAAQiHAAhug/IAAAAQDyETAAF2IAAAAQAAGckkEjIAAAAQkjEkmbAAIAAAAQmdAAkjkkg");
	var mask_graphics_174 = new cjs.Graphics().p("ApXNIQj3j2AAldIAAAAQAAk3DFjnIAAAAQhWAuhqAAIAAAAQitAAh6h6IAAAAQh7h7AAitIAAAAQAAitB7h6IAAAAQB6h6CtAAIAAAAQCtAAB6B6IAAAAQB7B6AACtIAAAAQAAB9hABiIAAAAQDTiXERAAIAAAAQEaAADYCiIAAAAQhHhmAAiEIAAAAQAAitB7h6IAAAAQB6h6CtAAIAAAAQCtAAB6B6IAAAAQB7B6AACtIAAAAQAACth7B7IAAAAQh6B6itAAIAAAAQhzAAhcg2IAAAAQDMDpAAE9IAAAAQAAFdj3D2IAAAAQj3D3lcAAIAAAAQldAAj3j3g");
	var mask_graphics_175 = new cjs.Graphics().p("AnqKwQjKjKAAkeIAAAAQAAj+Chi9IAAAAQhHAmhXAAIAAAAQiNAAhlhlIAAAAQhkhkAAiNIAAAAQAAiOBkhkIAAAAQBlhlCNAAIAAAAQCOAABkBlIAAAAQBkBkAACOIAAAAQAABlgzBRIAAAAQCsh8DgAAIAAAAQDnAACxCFIAAAAQg6hUAAhrIAAAAQAAiOBkhkIAAAAQBkhlCOAAIAAAAQCNAABlBlIAAAAQBkBkAACOIAAAAQAACNhkBkIAAAAQhlBliNAAIAAAAQheAAhMgtIAAAAQCnC/AAEDIAAAAQAAEejKDKIAAAAQjKDLkdAAIAAAAQkeAAjKjLg");
	var mask_graphics_176 = new cjs.Graphics().p("Al+IYQididAAjfIAAAAQAAjGB9iTIAAAAQg3AdhDAAIAAAAQhvAAhOhOIAAAAQhOhOAAhuIAAAAQAAhvBOhOIAAAAQBOhOBvAAIAAAAQBuAABOBOIAAAAQBOBOAABvIAAAAQAABPgoA/IAAAAQCGhhCvAAIAAAAQCzAACKBoIAAAAQgthBAAhUIAAAAQAAhvBOhOIAAAAQBOhOBuAAIAAAAQBvAABOBOIAAAAQBOBOAABvIAAAAQAABuhOBOIAAAAQhOBOhvAAIAAAAQhJAAg7giIAAAAQCCCUAADKIAAAAQAADfidCdIAAAAQieCejdAAIAAAAQjfAAieieg");
	var mask_graphics_177 = new cjs.Graphics().p("AkRGAQhxhxAAifIAAAAQAAiOBahpIAAAAQgoAVgwAAIAAAAQhPAAg4g4IAAAAQg4g4AAhPIAAAAQAAhPA4g4IAAAAQA4g4BPAAIAAAAQBPAAA4A4IAAAAQA4A4AABPIAAAAQAAA5gdAtIAAAAQBghFB9AAIAAAAQCBAABiBKIAAAAQgggvAAg8IAAAAQAAhPA4g4IAAAAQA4g4BPAAIAAAAQBPAAA4A4IAAAAQA4A4AABPIAAAAQAABPg4A4IAAAAQg4A4hPAAIAAAAQg1AAgqgZIAAAAQBeBrgBCQIAAAAQAACfhwBxIAAAAQhxBxifAAIAAAAQifAAhxhxg");
	var mask_graphics_178 = new cjs.Graphics().p("AilDoQhEhEAAhgIAAAAQAAhWA3g/IAAAAQgYAMgeAAIAAAAQgvAAgighIAAAAQgigiAAgwIAAAAQAAgwAighIAAAAQAigiAvAAIAAAAQAwAAAiAiIAAAAQAiAhAAAwIAAAAQAAAigSAcIAAAAQA6gqBMAAIAAAAQBNAAA8AtIAAAAQgUgdAAgkIAAAAQAAgwAighIAAAAQAigiAwAAIAAAAQAvAAAiAiIAAAAQAiAhAAAwIAAAAQAAAwgiAiIAAAAQgiAhgvAAIAAAAQggAAgagPIAAAAQA5BBAABXIAAAAQAABghFBEIAAAAQhEBEhfAAIAAAAQhgAAhFhEg");
	var mask_graphics_179 = new cjs.Graphics().p("Ag4BQQgYgXAAgiIAAAAQAAgcATgWIAAAAQgIAEgKAAIAAAAQgRAAgLgMIAAAAQgMgLAAgRIAAAAQAAgQAMgMIAAAAQALgMARAAIAAAAQAQAAAMAMIAAAAQAMAMAAAQIAAAAQAAAMgGAJIAAAAQAUgOAZAAIAAAAQAbAAAUAQIAAAAQgHgKAAgNIAAAAQAAgQAMgMIAAAAQAMgMAQAAIAAAAQARAAALAMIAAAAQAMAMAAAQIAAAAQAAARgMALIAAAAQgLAMgRAAIAAAAQgLAAgJgFIAAAAQAUAWAAAdIAAAAQAAAigYAXIAAAAQgXAYghAAIAAAAQghAAgXgYg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:289.2973,y:246.2751}).wait(1).to({graphics:mask_graphics_1,x:290.4534,y:243.9004}).wait(1).to({graphics:mask_graphics_2,x:291.609,y:241.5253}).wait(1).to({graphics:mask_graphics_3,x:292.765,y:239.1502}).wait(1).to({graphics:mask_graphics_4,x:293.9207,y:236.7747}).wait(1).to({graphics:mask_graphics_5,x:295.0763,y:234.4001}).wait(1).to({graphics:mask_graphics_6,x:296.2323,y:232.025}).wait(1).to({graphics:mask_graphics_7,x:297.3884,y:229.6499}).wait(1).to({graphics:mask_graphics_8,x:298.5439,y:227.2752}).wait(1).to({graphics:mask_graphics_9,x:300.6999,y:224.9001}).wait(40).to({graphics:mask_graphics_49,x:300.6999,y:224.9001}).wait(1).to({graphics:mask_graphics_50,x:299.5646,y:227.0376}).wait(1).to({graphics:mask_graphics_51,x:298.4297,y:229.1747}).wait(1).to({graphics:mask_graphics_52,x:297.2943,y:231.3126}).wait(1).to({graphics:mask_graphics_53,x:296.1589,y:233.4501}).wait(1).to({graphics:mask_graphics_54,x:295.0236,y:235.5876}).wait(1).to({graphics:mask_graphics_55,x:293.8882,y:237.7251}).wait(1).to({graphics:mask_graphics_56,x:292.7533,y:239.8626}).wait(1).to({graphics:mask_graphics_57,x:291.618,y:242.0001}).wait(1).to({graphics:mask_graphics_58,x:290.4826,y:244.1381}).wait(1).to({graphics:mask_graphics_59,x:289.2973,y:246.2751}).wait(1).to({graphics:mask_graphics_60,x:289.2973,y:246.2751}).wait(1).to({graphics:mask_graphics_61,x:290.4534,y:243.9004}).wait(1).to({graphics:mask_graphics_62,x:291.609,y:241.5253}).wait(1).to({graphics:mask_graphics_63,x:292.765,y:239.1502}).wait(1).to({graphics:mask_graphics_64,x:293.9207,y:236.7747}).wait(1).to({graphics:mask_graphics_65,x:295.0763,y:234.4001}).wait(1).to({graphics:mask_graphics_66,x:296.2323,y:232.025}).wait(1).to({graphics:mask_graphics_67,x:297.3884,y:229.6499}).wait(1).to({graphics:mask_graphics_68,x:298.5439,y:227.2752}).wait(1).to({graphics:mask_graphics_69,x:300.6999,y:224.9001}).wait(40).to({graphics:mask_graphics_109,x:300.6999,y:224.9001}).wait(1).to({graphics:mask_graphics_110,x:299.5646,y:227.0376}).wait(1).to({graphics:mask_graphics_111,x:298.4297,y:229.1747}).wait(1).to({graphics:mask_graphics_112,x:297.2943,y:231.3126}).wait(1).to({graphics:mask_graphics_113,x:296.1589,y:233.4501}).wait(1).to({graphics:mask_graphics_114,x:295.0236,y:235.5876}).wait(1).to({graphics:mask_graphics_115,x:293.8882,y:237.7251}).wait(1).to({graphics:mask_graphics_116,x:292.7533,y:239.8626}).wait(1).to({graphics:mask_graphics_117,x:291.618,y:242.0001}).wait(1).to({graphics:mask_graphics_118,x:290.4826,y:244.1381}).wait(1).to({graphics:mask_graphics_119,x:289.2973,y:246.2751}).wait(1).to({graphics:mask_graphics_120,x:289.2973,y:246.2751}).wait(1).to({graphics:mask_graphics_121,x:290.4534,y:243.9004}).wait(1).to({graphics:mask_graphics_122,x:291.609,y:241.5253}).wait(1).to({graphics:mask_graphics_123,x:292.765,y:239.1502}).wait(1).to({graphics:mask_graphics_124,x:293.9207,y:236.7747}).wait(1).to({graphics:mask_graphics_125,x:295.0763,y:234.4001}).wait(1).to({graphics:mask_graphics_126,x:296.2323,y:232.025}).wait(1).to({graphics:mask_graphics_127,x:297.3884,y:229.6499}).wait(1).to({graphics:mask_graphics_128,x:298.5439,y:227.2752}).wait(1).to({graphics:mask_graphics_129,x:300.6999,y:224.9001}).wait(40).to({graphics:mask_graphics_169,x:300.6999,y:224.9001}).wait(1).to({graphics:mask_graphics_170,x:299.5646,y:227.0376}).wait(1).to({graphics:mask_graphics_171,x:298.4297,y:229.1747}).wait(1).to({graphics:mask_graphics_172,x:297.2943,y:231.3126}).wait(1).to({graphics:mask_graphics_173,x:296.1589,y:233.4501}).wait(1).to({graphics:mask_graphics_174,x:295.0236,y:235.5876}).wait(1).to({graphics:mask_graphics_175,x:293.8882,y:237.7251}).wait(1).to({graphics:mask_graphics_176,x:292.7533,y:239.8626}).wait(1).to({graphics:mask_graphics_177,x:291.618,y:242.0001}).wait(1).to({graphics:mask_graphics_178,x:290.4826,y:244.1381}).wait(1).to({graphics:mask_graphics_179,x:289.2973,y:246.2751}).wait(1));

	// images
	this.instance = new lib.photo1527661591475527312dd65f5();
	this.instance.setTransform(0,-264,0.2966,0.2966);

	this.instance_1 = new lib.christinetrantaj1B4wkOCpIunsplash();
	this.instance_1.setTransform(-72,-340);

	this.instance_2 = new lib.maemu8Vh6ulKc50ounsplash();
	this.instance_2.setTransform(0,-156);

	var maskedShapeInstanceList = [this.instance,this.instance_1,this.instance_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},60).to({state:[{t:this.instance_2}]},60).wait(60));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(380.8,257.8,159.90000000000003,174.2);
// library properties:
lib.properties = {
	id: '741308FC6949FB49B03D954A70952D8B',
	width: 640,
	height: 480,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/photo1527661591475527312dd65f5.jpg?1602831424986", id:"photo1527661591475527312dd65f5"},
		{src:"images/2_html_atlas_1.png?1602831424973", id:"2_html_atlas_1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['741308FC6949FB49B03D954A70952D8B'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused){
			stageChild.syncStreamSounds();
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;